Add twitter card
okfn/wordpress-theme pull request #35
Opened 2022-10-17 16:07 UTC by avdata99

Fixes #34

This PR add Twitter card to headers.
I didn't manage to test locally but I assume it's ok

2022-10-18 16:10 UTC, gocemitevski commented
@avdata99 please test this locally with WP debugging turned on. I get the following error:

```php
Parse error: syntax error, unexpected end of file in /wp-content/themes/wordpress-theme/header.php on line 186
```

2022-10-19 12:33 UTC, avdata99 commented
I add some [curly braces here](https://github.com/okfn/wordpress-theme/pull/35/commits/3969b62f9d3ce75d75e25f28d9fc55b074a0446e) and it no longer gives the error @gocemitevski

2022-10-19 14:46 UTC, gocemitevski requested changes

2022-10-19 14:46 UTC, gocemitevski commented on header.php
> +			<meta name="twitter:site" value="@okfn" />
@avdata99 I think we need to use `$twitter_name` name for `twitter:site`, instead of having it hard-coded to @okfn.

2022-10-19 15:42 UTC, avdata99 commented on header.php
> +			<meta name="twitter:site" value="@okfn" />
I've found the `okfnwp_twitter_id` theme option. Maybe it's better. Updated [here](https://github.com/okfn/wordpress-theme/commit/9781662cf4f5676c8e4b721cc59541349eb99a7f) @gocemitevski

2022-10-20 11:48 UTC, gocemitevski commented
@avdata99 looks good.

2022-10-20 11:48 UTC, merged